### ISSUE TITLE
New model ready for testing!

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos1af5#9]

**Comment by emmakodes** [comment]
Hello @febielin @GemmaTuron 
### CLI
Model fetch and makes prediction successfully on cli
[eos1af5_fetch.log](https://github.com/ersilia-os/eos1af5/files/12013605/eos1af5_fetch.log)
[eos1af5_cli_pred.csv](https://github.com/ersilia-os/eos1af5/files/12013606/eos1af5_cli_pred.csv)
### Colab
Model fetch and makes prediction successfully on colab
[eos1af5_output.csv](https://github.com/ersilia-os/eos1af5/files/12013622/eos1af5_output.csv)
### DockerHub
model fetch and makes prediction successfully via dockerhub
[eos1af5_docker_pred.csv](https://github.com/ersilia-os/eos1af5/files/12013634/eos1af5_docker_pred.csv)

**Comment by GemmaTuron** [comment]
@simrantan 

When you have time please check that the model is working so we can close this issue

**Comment by simrantan** [comment]
Hi, of course! 

The model fetched successfully and returned outputs on all platforms-

**Colab**

Output: https://drive.google.com/file/d/1ZLSOkWvCTyl1f7ntNIT_WhHb_xtHARUD/view?usp=drive_link 

**CLI**
Output:
[output1af5.csv](https://github.com/ersilia-os/eos1af5/files/12074650/output1af5.csv)

**Docker **
Output
[outputeos1af5Docker.txt](https://github.com/ersilia-os/eos1af5/files/12074725/outputeos1af5Docker.txt)
